// <auto-generated />
using Hydra.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Hydra.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601000000_AddVenueBookingsEnabled")]
    partial class AddVenueBookingsEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
